/* This was generated by the program 'typegen' */
#ifndef INTTYPES_H_NETPBM
#define INTTYPES_H_NETPBM
typedef unsigned int uint32_t;
typedef signed int int32_t;
typedef signed int int_fast32_t;
typedef unsigned int uint_fast32_t;
#endif
